<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<meta name="title" content="exemple">
<meta name="description" content="exemple"/>
<meta property="og:title" content="exemple"/>
<meta property="og:type" content="website"/>
<meta property="og:url" content="https://exemple.fr/"/>
<meta property="og:image" content="https://exemple.fr/exemple.png"/>
<meta property="og:description" content="exemple"/>