<nav class="navbar navbar-expand-lg " data-bs-theme="dark">
    <div class="container-fluid">

        <a class="navbar-brand police-title d-flex" href=".">
            <img src="assets/logo.png" alt="TyroStudio Logo" width="50" height="50" class="d-inline-block align-text-top">
            <p>TyroStudio</p>

        </a>

        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <i class="ri-menu-line"></i>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link active" href=".">Accueil</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link active" href="game.php">Nos Jeux</a>
                </li>
<!--                <li class="nav-item">-->
<!--                    <a class="nav-link active" href="about.php">About</a>-->
<!--                </li>-->
                <li class="nav-item">
                    <a class="nav-link active" href="legal.php">Légal</a>
                </li>
                <li class="nav-item">
                    <a target="_blank" class="nav-link active" href="https://tyrolium-shop.myspreadshop.fr/tyrostudio">Merch <i class="ri-share-box-line"></i></a>
                </li>
                <li class="nav-item">
                    <a target="_blank" class="nav-link active" href="https://tyrolium.fr">Tyrolium <i class="ri-share-box-line"></i></a>
                </li>
            </ul>
        </div>

    </div>
</nav>